Weather app
hemantso/weather-app pull request #1
Opened 2020-12-03 20:12 UTC by hemant-soni-vst-au4

## Weather-app

- fetching up of weather API
- use of async await 
- webpack used
- linter use for good code

2020-12-03 22:09 UTC, bellom requested changes
## Hi @hemant-soni-vst-au4  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Changes Required! ♻️ 

**1. Let's work on the README file.**
Good, there is an instruction to set up the project locally but it can more helpful if you finish the steps, after running the `npm run build` the app won't open right?
kindly add instruction to open the app. (example: open dist file and open index.html on the browser)

**2. For some reason, the app is not working at my end both locally and the live version, could that be from my end 🤔**  

Kindly get your app working;

**Kindly watch this videocast code review below carefully;**
[Video Link](https://www.loom.com/share/765df2e0b53d4f848274f60d1147fb3f)
**_Hope it helps clarify the issues we are having ......_**

**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-12-03 22:09 UTC, bellom commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1",
### [Optional]

I think we don't need this line right?

You can remove it.

2020-12-03 22:09 UTC, bellom commented on src/index.js
> +function throwErrorMsg() {
### [Optional]

It would be nice to use ES6 and destructuring, instead of using the keyword `function` you could use `arrow function`

![image](https://user-images.githubusercontent.com/31897434/101092710-5ae3cd80-35ba-11eb-8dba-b9ba013dacaf.png)

https://microverse.pathwright.com/library/javascript-module-v-10/166782/path/step/97634944/

2020-12-03 22:13 UTC, hemant-soni-vst-au4 commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1",
yeah, it's optional. and for searcing city weather just enter the name and  press enter

2020-12-03 22:18 UTC, hemant-soni-vst-au4 commented
To search city temperature just enter the city name and press enter. it will work fine. Readme file is also updated.

2020-12-03 22:46 UTC, lekegitrepo requested changes
## Status: Changes Required :recycle:
#### Hi @hemant-soni-vst-au4 :clap: :clap:
#### You have done an incredible job :+1: The page looks great and the subtle animation added a good user experience. However, some requirements are missing. Check my comments below :point_down:

#### Application Behaviour:
- **_It should have a toggle control to determine if the result will be shown in Celsius or Fahrenheit *(There are two valid solutions: students can make two different requests for the Celsius data and the Fahrenheit data OR make only one request and use math to convert it to the other unit)* ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/search_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))_**

- **_It should change its appearance based on the received data ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))_**

#### Optional:
- **_You can add a ‘loading’ component that displays from the time the form is submitted until the information comes back from the API ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/loading_component_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/weather-app))_**

- **_You can add functionality to fetch the current geolocation of the user when the app is first accessed and fetches the weather from that location_**

#### _Reviewed by Temitayo Adeleke_

2020-12-04 03:14 UTC, bellom commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1",
@hemant-soni-vst-au4,

Well, I did press enter for sure, is just that the video can't show that I pressed the enter key😄 .

2020-12-04 17:01 UTC, hemantso commented
There is some problem with the live version it is not fetching data. But when we run with the live server by going to index.html, it is working fine. I will fix the live version.

2020-12-04 17:56 UTC, whiz25 requested changes
## Changes Required :pray:
Good job on this project. Your design is amazing. The search and toggle functionalities work well.
Let's fix somethings before we can merge and proceed.
- [x] the background should change based on the temperature value. currently the background stays the same. please fix that.


### Martin Afani

2020-12-04 18:30 UTC, hemant-soni-vst-au4 commented
Now background will change on every search.

2020-12-04 19:17 UTC, addod19 approved these changes
## Status: Approved :trophy: :balloon: 

Hi @hemant-soni-vst-au4, congratulations on an awesome job :fireworks: The project works as expected :+1: It's UI is beautiful :smile: 

Go ahead and merge into development :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-12-04 19:26 UTC, merged